
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "example5",
  "email": "example5@gmail.com",
  "password": "example1234",
  "username": "usuarioejemplo5",
  "avatarUrl": "example45.com"
}